### ISSUE TITLE
Normal map does not apply.

### ISSUE THREAD

**Issue by filibis** [SamuelTS/SketchUp-PBR-Plugin#1]
Even though i apply normal map properly, it doesn't have any effect in web browser, object looks plain (only diffuse texture appears).

![only_diffuse](https://user-images.githubusercontent.com/26340322/38448599-0d17deca-3a0e-11e8-8862-0aed75ae72ff.JPG)

**Comment by SamuelTallet** [comment]
Hi @filibis,

Can you please export this glTF file then attach it here? I can inspect it.

Thank you.

**Comment by filibis** [comment]
Here it is, zip includes .gltf & .skp (2017) files, diffuse & normal maps:

[brick_wall.zip](https://github.com/SamuelTS/SketchUp-PBR-Plugin/files/1886937/brick_wall.zip)

**Comment by SamuelTallet** [comment]
I got a more visible relief by adjusting normal map scale.
I hope soon plugin will include normal map scale control.

![brick wall with normal scale](https://user-images.githubusercontent.com/36248671/38505591-d6736da6-3c17-11e8-9d16-f0ca7caeb7ec.png)

**Comment by SamuelTallet** [comment]
@filibis,

Latest version displays normal scale. ;-)
Did you tried it? May I close this issue?

**Comment by filibis** [comment]
Hi @SamuelTS ,
I just tried and i think it improved 👍 

Also a suggestion about this: Can you implement a way of rotating/moving light or different lighting scenarios so that normal map feature pulls off its trick better? (See below video zipped)


[pbr_lighting_moving.zip](https://github.com/SamuelTS/SketchUp-PBR-Plugin/files/1973050/pbr_lighting_moving.zip)

**Comment by SamuelTallet** [comment]
I think it's possible to rotate light around model.
I would like a choice for environment lightning...
The thing is I want user interface stays simple! ;D
