### ISSUE TITLE
Emissive materials don't glow.

### ISSUE THREAD

**Issue by SamuelTallet** [SamuelTS/SketchUp-PBR-Plugin#2]
Does there exist a WebGL standard shader to render glow effect?
I need your help to make emissive material glow in PBR Viewport.

Target effect:

![Glow effect](https://user-images.githubusercontent.com/36248671/39474244-5150eb56-4d53-11e8-85d8-17d28b802fb0.png)

Thank you :-)

**Comment by pissang** [comment]
[claygl-advanced-renderer](https://github.com/pissang/claygl-advanced-renderer) has glow effect :)

**Comment by SamuelTallet** [comment]
> claygl-advanced-renderer has glow effect :)

Hello :)

- Glow effect is called Bloom in ClayGL Advanced Renderer?

- Can glow effect be applied _locally_ to one specific material?
I'd like to make emissive material glow, not whole model.

Thanks

**Comment by pissang** [comment]
Yes bloom is same with glow. 

Bloom will be applied in screenspace. But only pixels that are brighter than the threshold will have bloom. These pixels are usually from emissive materials. 

The following picture is also rendered by ClayGL Advanced Renderer. You can see there are two emissive balls with glow effect.

![](https://raw.githubusercontent.com/pissang/claygl/master/screenshot/claygl-logo.jpg)

**Comment by SamuelTallet** [comment]
I will try Advanced Renderer.
SSAO is a great addition too!

Thanks
