### ISSUE TITLE
How to create your own PBR texture library

### ISSUE THREAD

**Issue by pilou84** [SamuelTS/SketchUp-PBR-Plugin#4]
Hello 

I am using your plugin and also downloaded your PBR library. I was wondering if you could share with me how the PBR library was created ? In your library, all the files have an .skm extension. How did you create those files so they have the built in PBR configuration built in (height, normal, metallic etc)

Thank a lot in advance for your help

Sincerely

Pierre

**Comment by SamuelTallet** [comment]
Hello Pierre,

Follow these steps to create a SketchUp PBR texture library:

1. Create or select an existing material in Materials tray.
2. Open PBR Material Editor from "Extensions > PBR".
3. Apply PBR settings (metallic, normal map et cetera).
4. Right click on material in Materials tray then "Save as".

.SKM file stores PBR settings. Tell me if it's clear enough. ;)

**Comment by pilou84** [comment]
Hello Samuel 

How are you ? 

Thank you so much for the explanation, it was very clear and works beautifully. 

Can I ask another question, is it possible to add some transparency to the texture ?

**Comment by SamuelTallet** [comment]
Hello Pierre.

I'm fine and you?

Yes, it's possible. Add some transparency to the texture inside your preferred photo editing software. Save the texture as a PNG image. Import this image inside SketchUp as a Material.

**Comment by pilou84** [comment]
Hello Samuel

I am fine to, all good. Thank you so much for the reply. 

Would you mind giving me a bit more details on the method ? Nothing I tried work :(

I tried to add some transparency on the base color of pbr files and then add the texture in sketchup but it does not work. 

When you mentioned to add texture transparency on photo editor, where the texture file come from ? Is it from a pbr I insert in sketchup and export as texture image ? 
I tried that as well but it does not seem to work. I created a new pbr texture in sketchup, exported it as png, added transparency on photo editor, and used that png as a new texture in sketchup. 

Did I miss any step ? 

Sorry for the trouble.

**Comment by SamuelTallet** [comment]
@pilou84 You can add a comment if you still need help.
